
#spring:
 # datasource:
   # driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
   # url: jdbc:sqlserver://localhost:1433;DatabaseName=test
   # username: sa
   # password: 123456

  #jpa:
  #  hibernate:
     # ddl-auto: update
     # show-sql: true

